Polkadot companion for #8143
paritytech/polkadot pull request #2535
Opened 2021-02-26 15:56 UTC by cecton

2021-03-05 08:44 UTC, bkchr requested changes
I don't see any preparation for reusing the telemetry worker when being started from Cumulus?

2021-03-10 17:57 UTC, bkchr approved these changes

2021-03-11 09:53 UTC, maciejhirsz approved these changes
LGTM

2021-03-11 10:10 UTC, cecton commented
bot merge

2021-03-11 10:34 UTC, cecton commented
bot merge

2021-03-11 11:11 UTC, merged