Companion for substrate#9115
paritytech/polkadot pull request #3265
Opened 2021-06-16 10:51 UTC by koushiro

Companion for paritytech/substrate#9115

migrate the `Council` and `TechnicalCommittee` storage prefix:

`Instance1Collective` ==> `Council`
`Instance2Collective` ==> `TechnicalCommittee`

2021-07-30 12:00 UTC, thiolliere approved these changes
looks good to me, I tested the migration with try-runtime on polkadot block 6,163,183

2021-07-30 14:20 UTC, koushiro commented
> looks good to me, I tested the migration with try-runtime on polkadot block 6,163,183

I want to learn about the `try-runtime` tool. Is there a corresponding tutorial or document?

2021-08-02 15:52 UTC, thiolliere requested changes

2021-08-02 15:52 UTC, thiolliere commented on runtime/kusama/src/lib.rs
> +		TechnicalCommitteeStoragePrefixMigration
I mixed up the merge, those migration are incompatible, the latter migration are checking pallet version, while the former is writing the new version into storage.

2021-08-02 15:54 UTC, thiolliere commented
> > looks good to me, I tested the migration with try-runtime on polkadot block 6,163,183
> 
> I want to learn about the `try-runtime` tool. Is there a corresponding tutorial or document?

there is this seminar https://www.crowdcast.io/e/substrate-seminar/41
and this doc https://substrate.dev/docs/en/knowledgebase/advanced/try-runtime
most important is to compile with try-runtime and then use the subcommand associated

2021-08-03 08:28 UTC, thiolliere approved these changes

2021-09-10 08:27 UTC, kianenigma commented
/try-runtime queue --execution Native -lremote-ext=debug,executor=trace,runtime=trace --block-at 0xa7930a1fb28a1049ddfd50ea953674f9adf2d715b33a0b0a7678154e1bfba312 --url ws://polkadot on-runtime-upgrade live

2021-09-10 08:56 UTC, kianenigma approved these changes
Given that migration is tested.

2021-09-10 13:57 UTC, thiolliere commented
I run a successful migration with try-runtime with on current kusama and polkadot

2021-09-14 08:37 UTC, shawntabrizi approved these changes

2021-09-14 12:22 UTC, thiolliere commented
bot merge

2021-09-14 12:24 UTC, thiolliere commented
bot merge

2021-09-14 13:01 UTC, merged