make polkadot-runtime optional feature
paritytech/polkadot pull request #3820
Opened 2021-09-09 09:04 UTC by ordian

See https://github.com/paritytech/parity-bridges-common/pull/1053#discussion_r700312155 for the context.

2021-09-09 09:08 UTC, tomusdrw approved these changes
Great, thanks!

If we want to avoid accidentally disabling all of the runtimes, perhaps introducing another feature `no-runtimes` and throwing a compilation error in case it's not explicitly enabled is reasonable?

2021-09-09 09:31 UTC, bkchr requested changes
The code isn't adapted for these feature changes.

2021-09-09 10:01 UTC, ordian commented
> The code isn't adapted for these feature changes.

could you elaborate? do you mean
> introducing another feature no-runtimes and throwing a compilation error in case it's not explicitly enabled

2021-09-09 10:13 UTC, bkchr commented
I mean, if you disable the `polkadot` feature for the `client` or `service`, then both would not compile. But @tomusdrw requires the generic functions of `polkadot-service` for example to run it with its own runtime etc.

2021-09-09 10:18 UTC, bkchr commented
Ahh I see that all usage is hidden behind the `FullNode` feature. However I would still favor that https://github.com/paritytech/polkadot/blob/master/node/service/src/lib.rs#L1356-L1366 this is feature gated and all the other usages of `polkadot-runtime`. Like it is done for the other runtimes.

Same applied for the client crate.

We can just throw a runtime error if someone calls the functions and no runtime is enabled.

2021-09-09 11:36 UTC, bkchr approved these changes

2021-09-09 11:48 UTC, tomusdrw reviewed
Shall we add a CI check to make sure the `no-default-features` compilation works?

2021-09-09 11:49 UTC, bkchr commented
Fine by me.

2021-09-09 13:55 UTC, ordian commented
> Shall we add a CI check to make sure the no-default-features compilation works?

It doesn't work for `polkadot-client` and you will need at least one runtime when compiling `cli` and `service` with `full-node` feature.

2021-09-09 13:55 UTC, ordian commented on node/service/src/chain_spec.rs
> +pub type DummyChainSpec = service::GenericChainSpec<(), Extensions>;
not sure if this is correct

2021-09-09 14:15 UTC, librelois commented
It would be nice to use `static_assertions` to make sure at compile time that the features combination is valid: https://docs.rs/static_assertions/1.1.0/static_assertions/macro.assert_cfg.html

2021-09-09 14:44 UTC, ordian commented
We could also use `std::compile_error` as was suggested here: https://github.com/paritytech/polkadot/pull/3189#discussion_r646712678.

2021-09-09 15:56 UTC, ordian commented
@bkchr @tomusdrw please take a look again

2021-09-13 08:59 UTC, ordian commented
> Alternatively, could we patch the rococo-runtime crate and use a local version (rialto/millau)?
That way we could have both native runtime, without copying the whole node stuff over.

This PR allows only this approach, but you'd have only one native runtime if you disable polkadot and enable rococo feature.

2021-09-13 09:46 UTC, bkchr approved these changes

2021-09-13 09:46 UTC, bkchr commented on node/service/src/chain_spec.rs
> +pub type DummyChainSpec = service::GenericChainSpec<(), Extensions>;
Yeah should be fine.

2021-09-13 09:46 UTC, bkchr commented on scripts/gitlab/check_no_default_features.sh
> +pushd cli && cargo check --no-default-features --features "service" && popd
Enabling a feature defeats a little bit the name of this file, but fine :P :D

2021-09-13 09:50 UTC, ordian commented on node/service/src/chain_spec.rs
>  // This actually uses the polkadot chain spec, but that is fine when we don't have the native runtime.
```suggestion
// Dummy chain spec, but that is fine when we don't have the native runtime.
```

2021-09-13 09:50 UTC, ordian commented on node/service/src/chain_spec.rs
>  // This actually uses the polkadot chain spec, but that is fine when we don't have the native runtime.
```suggestion
// Dummy chain spec, but that is fine when we don't have the native runtime.
```

2021-09-13 09:50 UTC, ordian commented on node/service/src/chain_spec.rs
>  // This actually uses the polkadot chain spec, but that is fine when we don't have the native runtime.
```suggestion
// Dummy chain spec, but that is fine when we don't have the native runtime.
```

2021-09-13 10:26 UTC, svyatonik approved these changes

2021-09-13 10:28 UTC, ordian commented
bot merge

2021-09-13 10:28 UTC, merged