move to rust 2021
paritytech/polkadot pull request #4279
Opened 2021-11-14 01:13 UTC by NukeManDan

close #4277

2021-11-14 04:33 UTC, KiChjang approved these changes

2021-11-21 04:10 UTC, NukeManDan commented
`rust-version = "1.56.1"` introduced

For reference, I tried to get this to `cargo build` with 1.56.0 and it failed with
```
error: package `...` cannot be built because it requires rustc 1.56.1 or newer, while the currently active rustc version is 1.56.0
```
With `--ignore-rust-version` it _does_ build with 1.56.0, as expected.

2021-11-21 04:34 UTC, KiChjang approved these changes
it still gud

2021-11-21 05:53 UTC, Jaysonmaldx approved these changes
Thank u

2021-11-21 09:51 UTC, bkchr requested changes

2021-11-21 09:51 UTC, bkchr commented on bridges/bin/millau/node/Cargo.toml
> +rust-version = "1.56.1"
Please don't touch any bridges code here. That needs to be done upstream.

2022-04-22 07:39 UTC, drahnr commented
Closing, migration already happened in `645ae551fcce` .

2022-04-22 07:39 UTC, closed without merging