Refactor the big gitlab CI yaml file
paritytech/polkadot pull request #4906
Opened 2022-02-11 11:03 UTC by sandreim

This PR splits it in separate per stage files

2022-02-11 11:24 UTC, drahnr submitted a review, later dismissed

2022-02-11 12:44 UTC, sergejparity commented
Hi @sandreim It would be great if you can move those `./ci/*` files into `./scripts/ci/` directory. Actually we recently started unification of the CI related files in `paritytech` org repositories. More about it: https://github.com/paritytech/ci_cd/issues/313

2022-02-11 13:07 UTC, TriplEight commented
Funnily enough, we've exactly the same planned. Thanks for helping out here!

2022-02-11 13:22 UTC, TriplEight commented
Looking what might be wrong with CI config with https://gitlab.parity.io/parity/polkadot/-/ci/editor and it shows nothing useful sadly.

2022-02-11 13:27 UTC, TriplEight commented
As per [docs](https://docs.gitlab.com/ee/ci/yaml/#include)

> You can [nest](https://docs.gitlab.com/ee/ci/yaml/includes.html#use-nested-includes) up to 100 includes, but you can’t have duplicate includes. In [GitLab 12.4 and later](https://gitlab.com/gitlab-org/gitlab/-/issues/28212), the time limit to resolve all files is 30 seconds.

2022-02-11 13:42 UTC, sergejparity commented
Also there could be a problem with [**In CI, YAML anchors don't work with include**](https://gitlab.com/gitlab-org/gitlab/-/issues/5467).

2022-02-11 13:59 UTC, TriplEight requested changes

2022-02-11 13:59 UTC, TriplEight commented on ci/build.yml
> +    - job:                         build-adder-collator
`build-adder-collator` is `need`ed on L150

2022-02-11 13:59 UTC, TriplEight commented on ci/build.yml
> +build-adder-collator:
...and defined on L211

2022-02-11 14:00 UTC, TriplEight commented on ci/build.yml
> +build-adder-collator:
moreover it should be on the previous stage

2022-02-11 14:23 UTC, TriplEight commented
> Also there could be a problem with [**In CI, YAML anchors don't work with include**](https://gitlab.com/gitlab-org/gitlab/-/issues/5467).

this.
Here's how to workaround it: all YAML anchors should be rewritten to https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#reference-tags

2022-02-11 14:27 UTC, TriplEight commented
Oh that's a bummer, we can't use gitlab reference tags with `rules` keyword as it was included only in 14.3
![image](https://user-images.githubusercontent.com/17856421/153609107-be02081c-6230-4c60-a69c-c85b855e211e.png)
We're blocked here with https://github.com/paritytech/ci_cd/issues/171
cc @paritytech/ci

2022-02-11 14:30 UTC, TriplEight commented
I've made a testing project to lint this PR easier. https://gitlab.parity.io/TriplEight/polkadot-ci/-/merge_requests

2022-04-19 09:51 UTC, chevdor approved these changes

2022-04-20 16:20 UTC, TriplEight commented
We're unblocked, GitLab is 14.9 now.

2022-09-26 07:33 UTC, sandreim commented
closing in favor of https://github.com/paritytech/polkadot/pull/6031

2022-09-26 07:33 UTC, closed without merging