[Do not merge] Pipeline jobs optimizing
paritytech/polkadot pull request #4931
Opened 2022-02-16 13:22 UTC by alvicsam

I divided `test-build-linux-stable` job into 3 separate jobs: `test-linux-stable`, `test-linux-stable-node-metrics` and `build-linux-stable`
Also changed stages logic. Currently, there are 4 stages (1-4) instead of test-build-deploy-publish, and all jobs are connected using [DAG](https://docs.gitlab.com/ee/ci/directed_acyclic_graph/) in a way that all of them can finish during `test-linux-stable` run.

With these changes duration of the pipeline reduced for ~10-15 min.

The only thing that should be changed in GitHub is to remove `continuous-integration/gitlab-test-build-linux-stable` from required and mark as required these ones instead:
- `continuous-integration/test-linux-stable`
- `continuous-integration/test-node-metrics`
- `continuous-integration/build-linux-stable`

Part of https://github.com/paritytech/ci_cd/issues/326

2022-02-17 15:19 UTC, TriplEight requested changes

2022-02-17 15:19 UTC, TriplEight commented on .gitlab-ci.yml
> +  stage:                           test
better leave it on the next stage before we're on 14.2, but put in a artificial dependency with `artifacts: false` after something that takes ~ 15 min

2022-02-17 15:19 UTC, TriplEight commented on .gitlab-ci.yml
> +#### stage:                        build
just looked into an entire pipeline, this one is better be named `publish`, it doesn't build much

2022-02-17 15:19 UTC, TriplEight commented on .gitlab-ci.yml
> -    - ./scripts/gitlab/test_linux_stable.sh
guess we don't need this file any more, right?

2022-02-17 15:19 UTC, TriplEight commented on .gitlab-ci.yml
> +#### stage:                        build
and this comment moved beneath the following job too

2022-02-17 15:19 UTC, TriplEight commented on .gitlab-ci.yml
> +    - cargo-fmt
`  artifacts: false`

2022-02-17 15:19 UTC, TriplEight commented on .gitlab-ci.yml
> +    - test-deterministic-wasm
`  artifacts: false`

2022-02-17 18:53 UTC, TriplEight requested changes

2022-02-28 16:04 UTC, alvicsam commented
Closing PR because there were several changes in master, so I have to start from scratch. I'll create a new PR

2022-02-28 16:04 UTC, closed without merging