derive serialize/deserialize for xcm primitives
paritytech/polkadot pull request #5036
Opened 2022-03-06 06:48 UTC by stanly-johnson

replaces #4997 
resolves #4930

2022-03-07 09:55 UTC, bkchr approved these changes

2022-03-07 10:01 UTC, bkchr commented
@stanly-johnson could you please merge the latest version of the xcm-v3 branch into your branch.

2022-03-09 11:15 UTC, bkchr commented
And isn't this also missing v2 and v3?

2022-03-10 00:01 UTC, KiChjang requested changes
Actually, yeah, v0 and v1 are both removed in the gav-xcm-v3 branch, so we need to instead derive Serialize and Deserialize on v2 and v3.

2022-03-13 19:16 UTC, bkchr approved these changes

2022-03-14 05:44 UTC, KiChjang approved these changes

2022-03-14 09:09 UTC, merged