Adding `Fallback` on election failure
paritytech/polkadot pull request #5093
Opened 2022-03-12 13:31 UTC by georgesdib

Follow up on paritytech/substrate#10988

Use the newly introduced `BoundedOnChainSequentialPhragmen`, and `UnboundedOnChainSequentialPhragmen` for Genesis.

2022-03-21 10:47 UTC, kianenigma requested changes
`type Fallback` in our production networks should remain `NoFallback` since we don't quite know what are some good bounds. 

As for the `GovernanceFallback` as well, since this transaction can impose its own limits, I think actually for now we should set it to `UnboundedExecution`, because we don't know any 'reasonable static bounds' that we can assign to any `BoundedExecution` type. 

The missing step to figure all of this out is to create an accurate weight function for all of this `Solver` implementations, will make an issue for it.

2022-03-21 20:10 UTC, georgesdib commented
> `type Fallback` in our production networks should remain `NoFallback` since we don't quite know what are some good bounds.
> 
> As for the `GovernanceFallback` as well, since this transaction can impose its own limits, I think actually for now we should set it to `UnboundedExecution`, because we don't know any 'reasonable static bounds' that we can assign to any `BoundedExecution` type.
> 
> The missing step to figure all of this out is to create an accurate weight function for all of this `Solver` implementations, will make an issue for it.

I have reverted the changes including for Westend.

2022-03-22 15:33 UTC, kianenigma approved these changes

2022-03-25 19:49 UTC, kianenigma commented on runtime/test-runtime/src/lib.rs
> +	type VoterList = pallet_staking::UseNominatorsMap<Runtime>;
```suggestion
	type VoterList = pallet_staking::UseNominatorsAndValidatorsMap<Runtime>;
```

2022-03-25 20:33 UTC, kianenigma commented
@georgesdib thanks for making the bot work with your fork, helps with the automated process.

2022-03-26 10:45 UTC, kianenigma commented
Must look into why and how this caused benchmarks to break. 

Alternatively, we can merge this to keep the normal build of master working.

2022-03-26 11:34 UTC, georgesdib commented
> Must look into why and how this caused benchmarks to break.
> 
> Alternatively, we can merge this to keep the normal build of master working.

You think it's caused by the changes here? I tried to go back in time and see merged PRs from 2 days ago, and they seem to fail the same thing.

2022-03-26 14:26 UTC, kianenigma commented
hope I am not breaking anything for anyone, merging this manually to keep the master working.

2022-03-26 14:27 UTC, merged