update weights
paritytech/polkadot pull request #5098
Opened 2022-03-14 09:14 UTC by coderobe

similar to https://github.com/paritytech/polkadot/pull/5097, weights from different benchmark run as master & release branch diverged too much to apply the exact same weights patches cleanly

2022-03-14 10:55 UTC, chevdor requested changes
The weights should run using the production profile.

2022-03-14 10:55 UTC, chevdor commented on runtime/polkadot/src/weights/runtime_parachains_disputes.rs
> +// target/release/polkadot
This does not look good.

See 	[#[pallet::weight(T::SystemWeightInfo::remark(_remark.len() as u32))]](https://github.com/paritytech/polkadot/blob/975e780ae0d988dc033f400ba822d14b326ee5b9/scripts/run_benches_for_runtime.sh#L8)

2022-03-16 10:23 UTC, coderobe commented
the weights should now be in sync with https://github.com/paritytech/polkadot/pull/5098

2022-03-16 10:32 UTC, ggwpez commented
So this is now doing the same as #5098?

2022-03-16 10:41 UTC, coderobe commented
> So this is now doing the same as #5098?

Yes

2022-03-16 14:31 UTC, coderobe commented
Seeing that the weights have been reviewed in the pr targeting master, I'll consider them reviewed here as well. I'll be merging this once i have backported the frame_system benchapp weights from #5097 (waiting on results atm)

2022-03-16 15:46 UTC, merged