[Zombienet] test deregister validator
paritytech/polkadot pull request #5718
Opened 2022-06-22 18:23 UTC by pepoviola

ping @sandreim 
This add one test to check the correct value of `polkadot_node_is_active_validator`.

Thanks!

2022-06-23 07:44 UTC, sandreim commented
There is an error at startup - `Error: Invalid chain spec raw file generated.` Maybe related to `zombienet:v1.2.42` ?

2022-06-23 07:44 UTC, sandreim reviewed
LGTM

2022-06-23 09:40 UTC, alvicsam requested changes

2022-06-23 09:40 UTC, alvicsam commented on .gitlab-ci.yml
> +    - job:                         publish-polkadot-debug-image
```suggestion
    - job:                         publish-polkadot-debug-image
      artifacts:                 true
```
It's better to set this variable explicitly

2022-06-23 10:21 UTC, alvicsam requested changes

2022-06-23 10:21 UTC, alvicsam commented on .gitlab-ci.yml
> +      artifacts:                 true
```suggestion
      artifacts:                   true
```
Sorry, wrong indent

2022-06-23 10:25 UTC, alvicsam approved these changes

2022-06-27 10:12 UTC, pepoviola commented
> @pepoviola I've fixed an issue in the JS (the stash account was wrong), but the test keeps failing. It seems to be some sort of issue with metric fetching in Zombienet.
> 
> ```
> 1) ( Deregister / Register Validator Smoke )
>        dave: reports polkadot_node_is_active_validator is 0 within 180 secs:
> 
>       AssertionError: expected 1 to equal 0
>       + expected - actual
> 
>       -1
>       +0
> ```
> 
> At the same time I query the respective node metric endpoint and I get:
> 
> ```
> # HELP polkadot_node_is_active_validator Tracks if the validator is in the active set. Updates at session boundary.
> # TYPE polkadot_node_is_active_validator gauge
> polkadot_node_is_active_validator{chain="rococo_local_testnet"} 0
> ```

Ahh thanks for the fix! Checking the metrics cache now.
Thx!

2022-06-28 09:09 UTC, sandreim commented on zombienet_tests/smoke/0003-deregister-register-validator-smoke.feature
> +dave: reports polkadot_node_is_parachain_validator is 1 within 240 secs
We to check both `polkadot_node_is_active_validator` and `polkadot_node_is_parachain_validator`

2022-06-28 09:09 UTC, sandreim commented on zombienet_tests/smoke/0003-deregister-register-validator-smoke.feature
> +dave: reports polkadot_node_is_active_validator is 0 within 180 secs
Also here.

2022-07-03 14:40 UTC, pepoviola commented
ping @sandreim `deregister/register` test fixed.
Thanks!

2022-07-03 14:40 UTC, pepoviola commented on zombienet_tests/smoke/0003-deregister-register-validator-smoke.feature
> +dave: reports polkadot_node_is_active_validator is 0 within 180 secs
done :)

2022-07-04 07:54 UTC, chevdor approved these changes
LGTM besides the 2 missing EOF

2022-07-04 07:54 UTC, chevdor commented on zombienet_tests/smoke/0003-deregister-register-validator-smoke.toml
> +  args = [ "-lruntime=debug,parachain=trace" ]
```suggestion
  args = [ "-lruntime=debug,parachain=trace" ]
  
```

2022-07-04 07:54 UTC, chevdor commented on zombienet_tests/smoke/0003-deregister-register-validator.js
> +module.exports = { run }
```suggestion
module.exports = { run }

```

2022-07-05 12:18 UTC, sandreim approved these changes

2022-07-05 18:42 UTC, sandreim commented
bot merge

2022-07-05 18:43 UTC, merged