Remove debug_assert to allow Fungible(0)
paritytech/polkadot pull request #5765
Opened 2022-07-07 21:28 UTC by notlesh

This PR removes a `debug_assert` which checked any `Fungible` amount was > 0 only when converting `From<u128>`.

My assumption is that a `Fungible(0)` is valid. If that's not the case, then this should be enforced very differently (for starters, it should not depend on build configuration).

2022-08-18 10:01 UTC, rdovgan approved these changes

2022-08-22 12:42 UTC, KiChjang commented
> My assumption is that a `Fungible(0)` is valid.

Can you justify this? How is it currently not being enforced?

2022-08-29 22:24 UTC, notlesh commented
> > My assumption is that a `Fungible(0)` is valid.
> 
> Can you justify this? How is it currently not being enforced?

My main argument is that `Fungible(0)` is valid in the context where it is required to express something else, e.g. expressing a `MultiAsset` should still be possible even if you have 0 of it:

```rust
pub struct MultiAsset {
    pub id: AssetId,
    pub fun: Fungibility,
}
```

Furthermore, an instance of `Fungible(0)` may result from arithmetic where `0` is otherwise valid. This is how I originally encountered this; it was a corner case that I happened to hit in a debug build.

As far as I can tell, this `From impl` is the only code in the codebase which suggests that `Fungible(0)` is invalid, and it behaves differently between `debug` and `release` builds.

My suggestion is to remove it because it impairs usability, but I can understand arguments against this. If it is deemed reasonable to prohibit a `Fungible(0)` then I would strongly suggest implementing it and documenting it differently.

2022-08-29 22:53 UTC, shawntabrizi approved these changes

2022-08-30 18:12 UTC, gavofyork commented
`Fungible(0)` is not valid: A `MultiAsset` value must be an asset.

2022-08-30 18:13 UTC, gavofyork requested changes
Invalid.

2022-08-30 18:14 UTC, gavofyork commented
> My main argument is that Fungible(0) is valid in the context where it is required to express something else, e.g. expressing a MultiAsset should still be possible even if you have 0 of it:

`MultiAsset` is for expressing an asset. There is no asset if `amount` is zero. It is therefore an abuse of this datatype to use it to express "something else".

2022-08-30 18:15 UTC, gavofyork commented
> Furthermore, an instance of Fungible(0) may result from arithmetic where 0 is otherwise valid. This is how I originally encountered this; it was a corner case that I happened to hit in a debug build.

I'm not sure how you hit it, but the error is valid. If you need to be able to represent an amount of fungible asset which is possibly "None", then you should do what you would do if it were `NonFungible` and use `Option<MultiAsset>`.

2022-08-30 18:16 UTC, closed without merging