update weights
paritytech/polkadot pull request #6087
Opened 2022-09-30 14:31 UTC by coderobe

🏋️‍♀️ related https://github.com/paritytech/polkadot/pull/6025

2022-09-30 15:59 UTC, chevdor requested changes
Reviewing the values, this run seems rather odd compared to the several previous releases we had.

The weights in some pallets look great (= very steady as we are used to). For others however, we can see huge bumps and quite some from 0 to several billions.

@coderobe  we should start a new benchmark run. We can decide later to use the results or not.

I also would like to gather @kianenigma & @ggwpez's opinions on the big changes I spotted. There are more bing changes than whan I reported.

2022-09-30 15:59 UTC, chevdor commented on runtime/kusama/src/weights/frame_election_provider_support.rs
> +			.saturating_add(Weight::from_ref_time(5_508_430 as u64).saturating_mul(v as u64))
0 -> 4b

2022-09-30 15:59 UTC, chevdor commented on runtime/kusama/src/weights/frame_system.rs
> +			.saturating_add(Weight::from_ref_time(512 as u64).saturating_mul(b as u64))
800k -> 3m

2022-09-30 15:59 UTC, chevdor commented on runtime/kusama/src/weights/frame_system.rs
> +			.saturating_add(Weight::from_ref_time(1_829 as u64).saturating_mul(b as u64))
0 -> 11m

2022-09-30 15:59 UTC, chevdor commented on runtime/kusama/src/weights/frame_system.rs
> +			.saturating_add(Weight::from_ref_time(578_944 as u64).saturating_mul(i as u64))
0 -> 3.8m

2022-09-30 15:59 UTC, chevdor commented on runtime/kusama/src/weights/frame_system.rs
> +			.saturating_add(T::DbWeight::get().writes(1 as u64))
0 -> 3.8m

2022-09-30 15:59 UTC, chevdor commented on runtime/kusama/src/weights/frame_system.rs
> +			.saturating_add(T::DbWeight::get().writes(1 as u64))
0  -> 6m

2022-09-30 15:59 UTC, chevdor commented on runtime/kusama/src/weights/pallet_election_provider_multi_phase.rs
> +			.saturating_add(Weight::from_ref_time(6_883_886 as u64).saturating_mul(a as u64))
0   > 7b no longer using params ?

2022-09-30 15:59 UTC, chevdor commented on runtime/kusama/src/weights/pallet_elections_phragmen.rs
> +			.saturating_add(T::DbWeight::get().writes((2 as u64).saturating_mul(v as u64)))
0 > 280b

2022-09-30 15:59 UTC, chevdor commented on runtime/kusama/src/weights/pallet_elections_phragmen.rs
> +			.saturating_add(T::DbWeight::get().reads(1968 as u64))
0 > 29b

2022-09-30 15:59 UTC, chevdor commented on runtime/kusama/src/weights/pallet_preimage.rs
> +			.saturating_add(Weight::from_ref_time(2_441 as u64).saturating_mul(s as u64))
0 > 30m

2022-09-30 15:59 UTC, chevdor commented on runtime/kusama/src/weights/pallet_staking.rs
> +			.saturating_add(T::DbWeight::get().reads((1 as u64).saturating_mul(n as u64)))
0 > 25b

2022-09-30 15:59 UTC, chevdor commented on runtime/kusama/src/weights/runtime_parachains_paras_inherent.rs
> +			.saturating_add(T::DbWeight::get().reads(29 as u64))
900m > 5b

2022-09-30 16:30 UTC, ggwpez commented
A lot of the changes are probably due to https://github.com/paritytech/substrate/pull/11806  
I still wonder why for example the components here are now unused:  
![image](https://user-images.githubusercontent.com/10380170/193315161-67bbda99-199c-4469-8216-6be5501d39cd.png)


cc @koute @shawntabrizi

2022-10-10 12:09 UTC, coderobe commented
not merging this round

2022-10-10 12:09 UTC, closed without merging