[ci] fix check-transaction-versions
paritytech/polkadot pull request #6425
Opened 2022-12-12 16:19 UTC by alvicsam

close https://github.com/paritytech/polkadot/issues/6422
close https://github.com/paritytech/ci_cd/issues/694

2022-12-12 16:27 UTC, rcny approved these changes

2022-12-12 17:12 UTC, joao-paulo-parity approved these changes

2022-12-12 17:12 UTC, joao-paulo-parity commented on scripts/ci/gitlab/pipeline/build.yml
> +    - export LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/paritytech/polkadot/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
use `jq -e -r '.tag_name'` to extract the tag name

also need to use the `GITHUB_TOKEN` in the `Authorization` header or your request will be rate-limited by the GitHub API

everything put together:

`    - export LATEST_RELEASE=$(curl -sSLf  -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/paritytech/polkadot/releases/latest" | jq -e -r '.tag_name')`

2022-12-12 17:17 UTC, joao-paulo-parity commented
@alvicsam I see that https://github.com/paritytech/ci_cd/issues/694 is linked in the description. Is it by accident? I don't notice any change related to that in this PR.

2022-12-13 08:33 UTC, alvicsam commented
@joao-paulo-parity sorry, wrong number of PR

2022-12-13 08:41 UTC, joao-paulo-parity requested changes
Approved before by accident. I think https://github.com/paritytech/polkadot/pull/6425#discussion_r1046119264 should be dealt with before merge.

2022-12-13 09:50 UTC, joao-paulo-parity approved these changes

2022-12-13 10:22 UTC, merged