XCM: Implement a blocking barrier
paritytech/polkadot pull request #6670
Opened 2023-02-03 19:24 UTC by KiChjang

Rebased version of #5035.

2023-02-12 12:16 UTC, gavofyork commented on xcm/pallet-xcm/src/lib.rs
> +			ensure_root(origin)?;
Should probably be a configuration item.

2023-02-12 12:25 UTC, gavofyork commented
I don't think this actually does what it's meant to do.

> This type would include the `Suspended` variant meaning "does not pass this barrier yet, but it might pass in a later block" .

This meaning was not implemented. It will need to be integrated properly into the Message Queue systems (i.e. pallet message queue), so they stop executing messages from any origin which returns `Suspended` until some time in the future (e.g. the next block).

2023-02-12 12:27 UTC, gavofyork requested changes
I don't think this actually does what it's meant to do.

> This type would include the `Suspended` variant meaning "does not pass this barrier yet, but it might pass in a later block" .

This meaning was not implemented. It will need to be integrated properly into the Message Queue systems (i.e. pallet message queue), so they stop executing messages from any origin which returns `Suspended` until some time in the future (e.g. the next block).

As it stands it will do the same as it would for any other non-passing barriers: just drop the messages. Definitely not the intended behaviour.

2023-02-13 11:59 UTC, girazoki commented
I observe the PR includes a db read made by a barrier. I am assuming this could produce an unpaid db read, is it not that much of an issue because it can at most spam one db read per block? (I am assuming following messages processed in the same block will have the db read cached?)

2023-02-28 14:39 UTC, gavofyork commented
This should help https://github.com/paritytech/substrate/pull/13424

2023-03-19 13:39 UTC, gavofyork commented
@KiChjang you going to get this one over the line now? With the `Yield` error it should be possible to implement properly.

2023-03-21 17:26 UTC, KiChjang commented
Wouldn't this be blocked on #6271 before we can actually use the queues here?

2023-03-24 17:52 UTC, gavofyork commented
possibly, but it doesn't matter - the API is in.

2023-04-18 12:57 UTC, KiChjang commented
Will reopen this PR with some changes.

2023-04-18 12:57 UTC, closed without merging