Stop weighing XCM execution on pallet-xcm's send extrinsic
paritytech/polkadot pull request #7201
Opened 2023-05-08 18:53 UTC by franciscoaguirre

On the `send` extrinsic on `pallet-xcm`, we are currently weighing message _execution_ and then adding the weight from benchmarking the extrinsic. We shouldn't do this since we are not executing the message locally. A `BuyExecution` instruction will do that job on the destination of the message. We just need to weigh _sending_ the message.

2023-05-09 07:54 UTC, vstam1 approved these changes

2023-05-09 08:20 UTC, KiChjang requested changes
Sorry, but could you also add `SetFeesMode` to the weight expressions on teleport assets and reserve transfer assets?

2023-05-09 19:15 UTC, KiChjang approved these changes

2023-05-09 19:18 UTC, merged

2023-05-23 12:24 UTC, albertov19 commented
Hey @franciscoaguirre I'm guessing this will be included in `0.9.43`? This is making sending XCM messages from the relay chain impossible which is preventing for doing further testing (I hoped it was going to be included in `0.9.42`)

2023-05-23 13:40 UTC, KiChjang commented
I don't see the PR included in `0.9.42`, so yes, it's going to be in `0.9.43` instead. You'll have to talk with the release engineers about including this PR as a backport to `0.9.42` if it's really urgent.